# Generated by Django 5.0.1 on 2024-01-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmail',
            name='date',
        ),
    ]
